// frontend/src/components/AssetSnapshotOverview.tsx
import React, { useEffect, useState } from 'react';
import { Table, Select, DatePicker, Card, Spin, Button, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import type { Dayjs } from 'dayjs';
// import AssetTrendChart from './AssetTrendChart'; // 如有趋势图可解开

const { Option } = Select;
const { RangePicker } = DatePicker;

type AssetSnapshot = {
  id: number;
  platform: string;
  asset_type: string;
  asset_code: string;
  currency: string;
  balance: number;
  balance_cny?: number;
  balance_usd?: number;
  balance_eur?: number;
  base_value?: number;
  snapshot_time: string;
};

const baseCurrencies = ['CNY', 'USD', 'EUR'];

const AssetSnapshotOverview: React.FC = () => {
  const [baseCurrency, setBaseCurrency] = useState<string>('CNY');
  const [dateRange, setDateRange] = useState<[Dayjs | null, Dayjs | null] | null>(null);
  const [assetData, setAssetData] = useState<AssetSnapshot[]>([]);
  const [loading, setLoading] = useState(false);

  const columns: ColumnsType<AssetSnapshot> = [
    { title: '平台', dataIndex: 'platform', key: 'platform' },
    { title: '资产类型', dataIndex: 'asset_type', key: 'asset_type' },
    { title: '资产代码', dataIndex: 'asset_code', key: 'asset_code' },
    { title: '币种', dataIndex: 'currency', key: 'currency' },
    {
      title: `${baseCurrency}金额`,
      dataIndex: 'base_value',
      key: 'base_value',
      render: (val: number) =>
        val == null ? '-' : val.toLocaleString('zh-CN', { style: 'currency', currency: baseCurrency }),
    },
    { title: '快照时间', dataIndex: 'snapshot_time', key: 'snapshot_time' },
  ];

  const loadData = async () => {
    setLoading(true);
    let params = new URLSearchParams();
    params.append('base_currency', baseCurrency);
    if (dateRange && dateRange[0] && dateRange[1]) {
      params.append('start', dateRange[0].format('YYYY-MM-DD'));
      params.append('end', dateRange[1].format('YYYY-MM-DD'));
    }
    const resp = await fetch('/api/snapshot/assets?' + params.toString());
    const data = await resp.json();
    setAssetData(data);
    setLoading(false);
  };

  useEffect(() => {
    loadData();
    // eslint-disable-next-line
  }, [baseCurrency, dateRange]);

  // 修正onChange类型
  const handleRangeChange = (dates: [Dayjs | null, Dayjs | null] | null) => {
    setDateRange(dates);
  };

  // 主动快照
  const handleExtractSnapshot = async () => {
    setLoading(true);
    try {
      const resp = await fetch('/api/snapshot/assets/extract', { method: 'POST' });
      const result = await resp.json();
      if (result.success) {
        message.success(result.message || '快照成功');
        await loadData();
      } else {
        message.error(result.error || '快照失败');
      }
    } catch (e) {
      message.error('快照请求异常');
    }
    setLoading(false);
  };

  return (
    <Card title="资产快照多基准货币展示" style={{ margin: 24 }}>
      <div style={{ marginBottom: 16, display: 'flex', gap: 16 }}>
        <Button type="primary" onClick={handleExtractSnapshot}>主动快照</Button>
        <Select value={baseCurrency} onChange={setBaseCurrency} style={{ width: 120 }}>
          {baseCurrencies.map((c) => (
            <Option key={c} value={c}>{c}</Option>
          ))}
        </Select>
        <RangePicker
          value={dateRange}
          onChange={handleRangeChange}
          allowClear
          style={{ width: 300 }}
        />
      </div>
      <Spin spinning={loading}>
        <Table
          columns={columns}
          dataSource={assetData}
          rowKey="id"
          pagination={{ pageSize: 20 }}
        />
      </Spin>
      {/* <div style={{ marginTop: 32 }}>
        <AssetTrendChart baseCurrency={baseCurrency} days={30} />
      </div> */}
    </Card>
  );
};

export default AssetSnapshotOverview;

// frontend/src/components/AssetSnapshotOverview.vue
<template>
  <div class="asset-snapshot-overview">
    <div class="controls">
      <el-select v-model="baseCurrency" placeholder="选择基准货币" @change="loadData">
        <el-option v-for="c in baseCurrencies" :key="c" :label="c" :value="c" />
      </el-select>
      <el-date-picker v-model="dateRange" type="daterange" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" @change="loadData" />
    </div>
    <el-table :data="assetData" style="width: 100%">
      <el-table-column prop="platform" label="平台" />
      <el-table-column prop="asset_type" label="资产类型" />
      <el-table-column prop="asset_code" label="资产代码" />
      <el-table-column prop="currency" label="币种" />
      <el-table-column :label="baseCurrency + '金额'">
        <template #default="scope">
          <span>{{ formatAmount(scope.row.base_value, baseCurrency) }}</span>
        </template>
      </el-table-column>
      <el-table-column prop="snapshot_time" label="快照时间" />
    </el-table>
    <div class="trend-chart">
      <h3>资产趋势({{ baseCurrency }})</h3>
      <AssetTrendChart :base-currency="baseCurrency" :days="30" />
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElSelect, ElOption, ElDatePicker, ElTable, ElTableColumn } from 'element-plus'
import AssetTrendChart from './AssetTrendChart.vue'

const baseCurrencies = ['CNY', 'USD', 'EUR']
const baseCurrency = ref('CNY')
const dateRange = ref([])
const assetData = ref([])

const formatAmount = (val, cur) => {
  if (val == null) return '-'
  return new Intl.NumberFormat('zh-CN', { style: 'currency', currency: cur }).format(val)
}

const loadData = async () => {
  let params = new URLSearchParams()
  params.append('base_currency', baseCurrency.value)
  if (dateRange.value.length === 2) {
    params.append('start', dateRange.value[0])
    params.append('end', dateRange.value[1])
  }
  const resp = await fetch('/api/snapshot/assets?' + params.toString())
  assetData.value = await resp.json()
}

onMounted(loadData)
</script>

<style scoped>
.asset-snapshot-overview { padding: 20px; }
.controls { margin-bottom: 20px; display: flex; gap: 20px; }
.trend-chart { margin-top: 40px; }
</style>
